ALTER TABLE series ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE modules ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE versions ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE version_logs ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE documents DROP COLUMN created_at;
