// Copyright 2021 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by gen_zip_signatures.go; DO NOT EDIT.

package fetch

var ZipSignatures = map[string][]Modver{

	"0070ef7a948597230c7710d62b935cc5fa8bc610d5aae4d5e9c5dba7134b26b8": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.15"},
	},
	"00fc6544f83d90a60663df8b9067b9ce39ed66fe82c2a1b9759d4f41d00c4321": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.13"},
	},
	"01006cd4a7a3be6f1fdacfd2108596431302e40698ca2f87838c123f53f060ec": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.55"},
	},
	"012d1955932cc2931798f3a14a15f6ea5c96ec7b710282cd1280384c160da5bb": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.2.5"},
	},
	"012f15ae2babab5dc92f00e248b041dd83e33f8d80daab61a056ce870d50c204": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.9.13"},
	},
	"0193c97e31c2053651cfce4ee4e58590b49ce01d1b0b035b64aaef74d9ed336d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.35"},
	},
	"021d3944e21413f0de6e648bda6ecbb2e19f77695079b635098efbd1a2c29f4a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.4"},
	},
	"025173bb9b09e9a643221adbe57437d8b92fecffbe13b007a33c6b63391515b1": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.46"},
	},
	"02c072786da17cad6844fead29018c3e2496c1dd3204f1721115e815f1201337": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.6"},
	},
	"02f854e7a9f1c68ad114b8ed48c2aa1a6baae2566134e484a93f2d879f74fbed": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.20"},
	},
	"02f8fea651ab4b7f5be6b763dc31db552caad5ec71cc77f9bd499a45bf71e8e5": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.25"},
	},
	"03417e775446e2d1ad0e1da4f420cb14d0a893445eb311dd8ce2e012f00f71fe": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.5"},
	},
	"047014c07bcf3045c902b061654e5c29c2deae1a8b7cf4342c20964106549370": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.23"},
	},
	"04730a4257855f348c5893d52bf9cf8ef61b7d2599d3cf0077885c5b0dafc73b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.23"},
	},
	"0564efa92a7f5ebf8a063f033463f490442e4ecb5c03c5c4b33432e0086580d1": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.10.3"},
	},
	"077a871764f48534cea9cb0c1b711941b1ef1c8798d5fe1ed4231318fcc1d25e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.16"},
	},
	"0813a1321df36deceb3727ee60b8e61bdbae3602bad60a4c488a7fb07e1b45a5": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.36"},
	},
	"0a510b9459b94608cc366fdb64bcc9069326c71430887440bbdb06709e915fea": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.34"},
	},
	"0ac7d7731d2666c93a625d0be7cfd7835bc807ea3eeebbdc906c37103a38cc39": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.40"},
	},
	"0b10c7483ad896c345f11a3db33eda4010c25715980b215d0db0aba031c88153": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.1"},
	},
	"0b2025f63c87db6396f4cd3127c94b076316b920bdf2b24d5aceafff64ba5cd7": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.5.1"},
	},
	"0b469b69e2fe0505040232f1a68d284ff06e3e3167f6ce2a491040a4c721ebc2": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.41"},
	},
	"0bdd0a29dbe2be132d2f4b642cd9a7447b1da7c10f682f4028f68f519b58e733": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.60"},
	},
	"0d5d957fb29b98a0332c77b43dbdd96e372996145171930b075ec3b70c6a57cf": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.5.13"},
	},
	"0d757d537428e4fe3bd2faf887391e3d11d9321c42d60aaafe79ca9ca872f159": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.27"},
	},
	"0d89995fa86e776a1b3d5b06ec1bb0bbe3f44154a7f95e27c7ec3424368cae2f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.11"},
	},
	"0df4d9c70273379b9b5f2b16b0e39abb8ec2e4ce83bcd1662194d3b69c807305": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.6"},
	},
	"0f4a0214145f3858d6ae99a82b1929cd8c69e2daa133e135fab64bbcb178689f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.6"},
	},
	"0fbebe6ff81e4714160ce14daec7f110db3a392640932fc148e771f22cb788a4": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.8"},
	},
	"0fbf79157bc496154ab2982947e24c0dd91aa0f34e65f60c5322ed9cf9cd6674": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.46"},
	},
	"111ccccfe6b265f392d87cd9a5df2708406e4f779e3674d2a8b270a2eace4022": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.40"},
	},
	"1343849bf083e0df8a0d59f74e79ed5d144a5da54cc8b2439f97efb32d42d078": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.28"},
	},
	"138df3d1f4e0a6bd4fd15e41d81f9ae2200ded75e49bc911a612cb77f55921de": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.39"},
	},
	"13a1bcfb4daed19f6f0a1198442a8d08caa0a952ffd6617e6a44fcf2b4a3ed46": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.0.1"},
	},
	"13fcff91d5e2487c134dd1e66d6a6ec11b15f42965794bf287d31d3ed05ba039": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.33"},
	},
	"141aee89654032bbe8206e0b899390043136612d59de542455794fae8d2592fb": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.17"},
	},
	"148fb5565f186c8a76fd373567af1743a4e52437bc5e4f43489e136dd1950a94": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.51"},
	},
	"14ffed9e9b4e8a87c4c0f2293dee4512793782084d5e841e6f657a4fff3e96be": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.9.11"},
	},
	"1591e025384941bdae088d0bf275e6d4318f1473dcb711baa758264809c9f161": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.6.1"},
	},
	"1602a28be9cd4d8e72e90a4e97a6f2018db42a780894841adcb8f33ea3f448fe": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.17"},
	},
	"161f220fabecd1439a7ec6b78ebeacc9ca7aa174227f6b4963a73fb55a436cb1": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.79"},
	},
	"1695ebca04185f37e47dc945cbc3dddda0fdc6173e12e5fe388720d0614a51fe": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.1"},
	},
	"1793ebeb93ada3c48092edc099472f5bba311848bf7b1536b619c52970382d35": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.12"},
	},
	"179d1a966d113086ef41304821feb882ba9d2d611eff049711ad049aeb0c428d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.12"},
	},
	"1815142fa55753742fd728b42f35ba0410336314165d083dc1c13e7d0c07b1a0": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.0.7"},
	},
	"1862f20e3fc7331d33f2d0b8814ff799e67b57b2c47277ac812f96f49729f2a5": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.6.3"},
	},
	"19612dcf543ac53ec07e39d22d14c523815082dced201916d5ee7762b1108074": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.7.8"},
	},
	"1ad7ea9a140faf7e5abab6dd2a1c3be14d702b048824ed57a6af3add60ef2aa5": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.5.0"},
	},
	"1b893f297c24cb18c75043e3604ce3003405d4018cc2cc4f1ffd49c3bd8c3ec9": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.0.11"},
	},
	"1c1f7d938afac43062e33e015b5f9c72363492ddf1a790c1bf932cc8e3fccaca": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.1"},
	},
	"1c973d1fff85d26a47b9802063c0c571a881430eb2ac858cc2f41921d23d4e0e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.10"},
	},
	"1cdf2833181e6ada353085899360b379207ff1d7174a0cf6b145e9dbe4cc35ac": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.6.7"},
	},
	"1cfec04c24662f042a524c859ecb71091496827edd56a77a7d61b5d5f46cac22": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.14"},
	},
	"1d1bd99404a30dd0c6dc522de74dae93e9f8751a48760601e5bd79d8ec226a56": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.37"},
	},
	"1da2c97642952213538a8e6cdaa6c425f2fb31922d20685806856cf734eec25d": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.9.14"},
	},
	"1e0fad7d8718ca2c4e6a40fb602fb25d3ad614bbee768d79dedff59a477bcb25": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.32"},
	},
	"1e0fee6d5ecf83e6b9870d5d1bef0115049bcb60216218defe54576418227e69": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.36"},
	},
	"1eaa8dab0ed6cf3020eab12c962c6d450599762b4118393693c64c7e56bd8dd3": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.45"},
	},
	"1ee2cfc0a11c390786deeae93ea7ce1691b7acbf26dde1b20cc08deeb02ce75a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.18"},
	},
	"1f7cabc463bcc2e0e1bd580a57aef1de1a816c9dd29aa009221d54f5f4b7a9df": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.21"},
	},
	"1fcd663acf1965e3af7cb000885ff49768afacc9363a6f926b1b24354797a5d0": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.0.3"},
	},
	"20f09d91e08f4dfdc23c85a282a8a6f360abd42711672d902b29f4a936bb92b0": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.24"},
	},
	"21486f3378f32b701f83c7b02081f1123ed2ffdb10c9b13b02fba404f10bee96": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.7"},
	},
	"21d38c3c8b560ecd68d6b3cc9ba4e5f5067e4294f09c1420493bdf6690981703": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.5"},
	},
	"21e57c9b4b781012fd6ec7c58386a022f011a8a3239af44be6b4deec2a0a63c3": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.0.10"},
	},
	"21e8cd93fb60ac8271970b6628316979abb20bd5c8822b1310477a0789598927": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.41"},
	},
	"21f190fb2b62f496de781ff69c82687fbe8ca473f5c29ed8b16ec204c269fdfe": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.38"},
	},
	"240c9cec5f30b638d332eef6e4f9f54554b1f0c4fc13066de05844d35bdb65be": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.60"},
	},
	"2769f57b7e09852c1dfe1fefc5b531857cbcfc689a70e64760b524773295a307": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.22"},
	},
	"282557411d1cc5191e0888532eefce242f0e8a059388b82d3e735e94ebffad81": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.30"},
	},
	"28de334f03b2e25cfc9a14865de8a454dbdde4bfb464742ae2100f7161c48fdf": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.10"},
	},
	"293cdd551c271da4ba2d12c3d65361e4f1ba794262cb2109c2fb1b7e15a0fa06": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.14"},
	},
	"297c06fb895dec1030098623338c9abfe432c84fb61810b2ba0a7ab61a578af7": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.7.3"},
	},
	"299d627af7aac09f73aa88f5d9860f2dce27cb558412bf9c8fd4dac5c52e61b7": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.26"},
	},
	"2a2e3ca5184ae9c76ee11cf263973db2e47d5330ec495c7237c32560d9a58cd0": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.24"},
	},
	"2ad1323938136b47a98527cd3ae3a1d5c023ec8757f56d0ff85172764a0defd6": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.7.1"},
	},
	"2d578222931bfc313a686e03b6aa7332253b41f92b52c30b60a684c82dad828f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.2"},
	},
	"2d812b679bceefde22b9944e888a924922ab3e434fd515bc96a6cddf22259225": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.44"},
	},
	"2dde72dd1df899557706b393ab4ab3caed903bc5f75d8593a9e6d970aba14858": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.8"},
	},
	"2ed954440e7319af0838fa3f57b90ab85af32de152ca4f7888b6fcc2db2dacc0": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.4"},
	},
	"2f0db689e0d466e269ed1b7c23736419765799a3b26bb798e41ff5fd3980a525": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.13"},
	},
	"3051ec527081bc3aeb64dce8f591eed1b9431c1cba594e8ec8275184fb2d8f7f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.26"},
	},
	"328febad29b3a38937231b2838dacb6dfa508a66abb789917a1b566525cf61bb": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.19"},
	},
	"32ca284475908376c2468290a22cd45cdba289090e19c3fff70f87e1df354634": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.43"},
	},
	"33818140d49c09a42929cf8afc654f340ee6c6e62f103d4afd9a512ed338ed94": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.34"},
	},
	"33fddb8dbf05fdc6f75f76cec2c4446dc5c56208a5c7661797f29cd01e6c48b8": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.10"},
	},
	"349efb73c7cd02881c5166f2547854d36940c9986e7305efa08e0fe850e7bfe6": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.57"},
	},
	"359cd9dcf0c1da4bf0f757c76f9442699d560f3a3aac1537b4b49bdc6467433b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.49"},
	},
	"35dd6d0a81f5e9b1550c572ba4fd20950663c17a6f04f4350b4c697aa03bf60b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.43"},
	},
	"36a928e5832de287da1175156d841fc634322218638299d395dd8952f8996c22": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.23"},
	},
	"36e2cdd881505efc55ffe272e8f5ee0f41fe3137ac5d62f4dd2dd4b3340a04cd": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.5.6"},
	},
	"3824ed404dccb537228ff17c2a4ec12265bb2ece53fd68aace0288957600a5f5": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.8"},
	},
	"38bcf45c954fad3a15ab68d419e5a3b9187106d1c07b6087f04a79f2ea337709": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.6"},
	},
	"38d2e07504b4bce0f9fb84e422495674b4c76c1013e45cedf7b98b60f11a0bce": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.6.0"},
	},
	"38d558e46e9de0b75a55e60a93e028673deca04cf53d45d41203c0a4e415c1c6": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.23"},
	},
	"391efbfb5e997f9f2857cda24b866e3c3bb17b33fd4d9d811fdc792a85810f7b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.5"},
	},
	"39c46fd0873c5c87d9651b5525299ca6622924a0a355653c76d413f6292c9c03": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.0"},
	},
	"39faed0060d6e20e7e31d6226adcae4f902d5c5f51ba35c654532dc3b87f5662": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.16"},
	},
	"3acc6e304818224d548c3927717336d4dd992ff4af1fb2b95735f397effcc85b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.24"},
	},
	"3b371010d16ed29cb686eab34c12cc28846fbb89cbcca5328b858f717b372e81": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.16"},
	},
	"3c60dfeaa67f1fb812bfcc0097d9f14b22349556a21968ae016125c307884fdc": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.4"},
	},
	"3c85c82d7e9f8a90d6e86f1dcab35468913b1b6896fdfdb705251f09d8dd2fac": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.9"},
	},
	"3cce72f99827c2a753724d84f44a334b52b05dae929359054c1769081063ea4e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.0.0"},
	},
	"3cd9d93645925be3648b76f535b7390a7f4fc5ab031b98f711f2e1c657573f50": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.27"},
	},
	"3d0b4dc4bb28cc889e57ababba4a8c0311c18194d514bcd8a18e1c6c8a43ecc0": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.25"},
	},
	"3d6e8ffdc311a9e349ae5e7d151ad74e0247fbda72bcc33b6771e8a8710cec28": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.0.9"},
	},
	"3e5501923bebac98d7da4aad12c4ca10c44fd246e53cd1c91ed9e56a8bfc1e9f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.0"},
	},
	"3e921f75fd36b0fd9d8d48a5a132450bff0fd7a22b58cd036e75e231bf3be118": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.76"},
	},
	"3f17fb46ffea8eed4ad3ac53d098f13eb242f97a4b77e46ee5305530d6844b82": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.0.6"},
	},
	"3f185941761b8794dedd71f58b53cc5e43f42cf378a5f502af15d56da93b3688": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.9.6"},
	},
	"3ff68a00d41d69f84764dd0494f9b5f4afb285fd775d1dc45813463e391f3073": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.19"},
	},
	"40ff69b3cb2d2ffaef8a73747db843d5e5337c389ee52e3d71c192d212f99adf": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.4"},
	},
	"4101f3452461e5871c610f295f2195517bf4d16e0bf751aa2e97aa86cfd99142": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.50"},
	},
	"44514d3926da9e7fa2eb33b82eac42376c68f4e6fe9f45630b20c5d2391a82bb": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.11"},
	},
	"448e33d2e0806f43a9aa3dbc1361b282ab5f46f90aa9807761ce98df3132e05d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.6"},
	},
	"44b25449949fcfbc5e9270c1cf99a7425a66d45d1ccb7d3344b04c9ec6584184": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.15"},
	},
	"44f08b8095412f3b1e954a6265a57b79340edb2586f012f30581b5702436bc5f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.57"},
	},
	"45984709ed51d4af5fcaa20772cb97fb81c87775488d83f7c7d6d4bbabdc9d77": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.31"},
	},
	"46143f5bd84f61d087c45914555bdf0935ba703d23bec068f133ddbbd5c628e7": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.43"},
	},
	"462fa3303e4f5055abc34add02ae8e436b8873167beff60144d3a3712634562d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.19"},
	},
	"46d5a07a19f6981d03806d3230ad6c10b58929bc8d8c940a0383cbf065eabb95": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.0"},
	},
	"49108d3bd57f6f3611597cf8e538514f0c0864dda345838b518f4da5bff6ca53": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.1"},
	},
	"499ae540e8368f072ad7abe1d00e17570547c76839a2a04242efa0875c8557fe": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.0.2"},
	},
	"49e238c82492767b23983e1137c8c4f9d1875b44b33a4ca04684581449756fe4": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.51"},
	},
	"4b0d0d28927489d358eb83eeeaeaf21861b87a37f3f538bad768eb7dc2adf0db": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.2"},
	},
	"4bed5f2a761e4084a7e6fb241da7a6c12164362fa7aacf6dfc6842a2f16a3c87": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.28"},
	},
	"4c05588eb813098d097a625727806f5a60d91b2d9b625473ba7126a975567551": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.5"},
	},
	"4c852c6129709e73ab115ec0fb4983a6d2039fdefbbfa22c7b5bbe181bb3a950": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.10.1"},
	},
	"4de106a9fb451cf6eb91d8ad08e7f5e69a78eb9bc0d003ab04738c82a312861e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.56"},
	},
	"4e43cc9078f8b52483fc9404293ad6dfcfa2bb8d921bd8edc8df978f96df9e7f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.27"},
	},
	"4e942b85f9860ead36ff2fa78577a351ae4958bf953bcafea8e12a10a647e3f2": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.18"},
	},
	"4f32d3f18fefac3af6c3e0ffbb8cd372ea467663daf63bb83b457672e511080e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.2.4"},
	},
	"504c699600fc0bb03fe65e7ef2b0e969af65574df246397b22e08d30f00b6e4b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.12"},
	},
	"506b12466c485998bebf400068365c3018b2c47c77ad85d138aadc32f10d59a9": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.3"},
	},
	"50c24a59af1f79f5211c0ed17d12b0ce53a414f0562dad817a9527fa47d48b33": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.13"},
	},
	"50e8385c3900c7bcf9c20838d9214be60a738b369c14e7b3bb13bcd09d074c37": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.2.2"},
	},
	"51a6cf99048dc226e1952055442df3d9e995cff52723e3f04b27f00972cd440e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.27"},
	},
	"52b9e2f8f8817e65f723bfb03caa056eb8410c008a01b932e5989e68dd1a2bb3": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.67"},
	},
	"53459784c777e76f487c94d39350a6d3308ec452d7d7319013fadad7ee927f05": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.44"},
	},
	"539a0beb52fa91735ce033b3cc238109e62c793b450bb632b557a9f522f69fda": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.20"},
	},
	"53c21cde40a2c0ff5b75bd7a1c48225fc7f30522ef3e766e366c8a3009813697": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.38"},
	},
	"53fc9e80e8c84b4fa37d5c0a974ec6a62d6af083155ace44eddb81abd4e90b4a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.22"},
	},
	"5413e2c36eb312371f9769969ba2e2260072f3e65d68e5df08c195d383de2de9": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.1"},
	},
	"541b1501ff913215936e6fec65337b259587d063211731e99ca9a612cc26e497": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.9"},
	},
	"546625924bddd0653238b2a24917ae24f389c9a6d05377b4ab7f3c94f00a8f1f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.2.3"},
	},
	"557cf5fdf4e651e8383981e159fe77e097a9e419ece86416372f2d781949b4c5": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.45"},
	},
	"55ddf50d68d3f453d7c78f891cd4359bf0294419b00bd70e92fad19c215d8fc4": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.7.7"},
	},
	"56ce50014cc8739b24601964245fbb21da1a73c91100067dc8380beb83e9a478": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.22"},
	},
	"56ee2cc1ab43dd75cb4913b8bf2c3b4020d0fa48ff81c4f96f01a9027603e563": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.78"},
	},
	"56f7e9ad880268a73e10595126df7dd485f73fd9a4ef3ab5cc48ca2df8d84cf6": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.2.0"},
	},
	"576686c413a425925bd4d300122efa9af5fadb908a2bded181fff975dc44315a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.5"},
	},
	"57d7524ce029015dc8b34d2faf34650eaea4b063de7b3a2c504c69c463c15b80": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.10"},
	},
	"585d0d3082110684bc2f1a2287fcbeca2d36ca3d7cfc986bee425da5eb5dab37": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.44"},
	},
	"587382b9426c6d38f1ad71407d3e22202190dd3d73e60a0a1ed327911e7bfc30": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.7.0"},
	},
	"59bd900cef030cbee1eda510fbf75a78560765cea200ea5667f6dcd0ceadba6b": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.9.16"},
	},
	"59c3ae174388647d37586a845542ff202e9c8d64ac885a8d5446387f35169dcc": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.9"},
	},
	"5a375386828105f37d370d8970ed04264c9b5b1429f99c791b8f2b8c6af81a4d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.22"},
	},
	"5c020239be9374d6109856230dcda18ba91dcee786f4147d7c35706121e4e716": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.52"},
	},
	"5c385baaa09fb7e970d88821c3dc51113475330899b0be6b364e8db2efde0afb": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.1"},
	},
	"5d7711889af5018a6f13240c1272bb6799e0c94524fd0f048586114ddb8abeaf": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.32"},
	},
	"5de491e17e39412c1ae3e6f8e9aadb21ccddafb8695e2b73dc100a67060365e7": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.14"},
	},
	"5df9612b3f4b8262b246f042c8454b2e2e2cc0be8579e2429e9b02f8ac153bc5": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.35"},
	},
	"5dfc0a5960e96c5380bf40ff09bf43031b33fa25ea52d0b2d49db7d16151750d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.17"},
	},
	"5ecc3f8dbb870a194175e7fd55cb40a40f72811596702e3401e35def698243a9": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.29"},
	},
	"5eda578e84a5bf023a60095deb83fdc54524e2405f14deea4a7e78531bef64ed": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.9"},
	},
	"5f178588498824e28deeb24eb55b94e9dc29d5a6f32fde89c50189cf77f17b46": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.7.1"},
	},
	"605b96752d5e1a3f2f3e25b6669b04bde966155ab99ac01920aa646fcf7e0c9a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.21"},
	},
	"62258ed5f9006c441b162271b04a3e0ee1beaf669760d664f13e21eb4eb7d1df": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.10"},
	},
	"62df505ace076f2983fb09afe07316776893e6886d7a2c23366ba6dcc1b2bd19": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.53"},
	},
	"62f2276a2c5bd9761f35720679e7b5354deb8b3bbfa20eeeffec3055483cae08": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.46"},
	},
	"6330413bdffed6b02e030b312846d85f773b6f0c362803e41174f3b2445821cc": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.20"},
	},
	"63cbd989a0c361ec2f1a90c39b3b9d14c3a9d6b5c2b0f49c61459d11ea48423e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.47"},
	},
	"649833f6183f125b0edfb6865f9f467a78c84d2813de598c8dd718405b6b9a63": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.8"},
	},
	"67005e3acade9eb0be4ab95b47fa1d415358c073e1459f47e953b230d3e01b5b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.8"},
	},
	"6753ffe24b836b7b182d91b7593a320a4da7aeb5841ad0b4f2062c2d3d47e189": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.17"},
	},
	"6977df55401f087976ba4ffbe06db75d50e89d085e7021d440b5d8ebbc121d1b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.12"},
	},
	"6a3deac9c66210d882c51e6c0d8bd84e9e8cf4293bc2ccb69e2578b594327190": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.5.2"},
	},
	"6ae51447a01200e3c4adf6aed29b33a9459d0f8f12cf58cfe2824a8c71ce3137": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.7.5"},
	},
	"6b151eb5c5a98e6f06f8f46bbec53e45c63620566e9980f7e2a638feaf644994": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.72"},
	},
	"6c33deaa6911273e87d15d3b8bc56d0b9caa7d2c4cef1f0617720ea598821d2f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.37"},
	},
	"6cc67d190cac79e8d38d6b4fee0e876e5e078bc31f996b3854cda853578724e1": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.3"},
	},
	"6d67c8aefedee863ec0efc2cb61af89ae74f39f509647207ab844f6a8b5f505b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.17"},
	},
	"6dc02204e16ceb5a23e24be21040ba20e411a9f097509b6c1223c79e193def06": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.77"},
	},
	"70d1133a3b946e662ad336b65987ca61226744135edd6a11b2e164d37b27846c": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.59"},
	},
	"71db83340849d913fc05e1578740417f8c799acf290ad46e83cf4243f53b8bb8": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.54"},
	},
	"721160692fcb6bdea166608298f86b36be57f9f383c78b049158e36194fbc40a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.48"},
	},
	"72334b50c369aeba7c280d2b1c31a9cce335e94b83e212e074f8154930b69f1a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.25"},
	},
	"7256b46eebe8585d57163f8c40ace06aa407fcf0e4748112f33d76e8d10c170f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.30"},
	},
	"7264045f9155641b5b64d64e36072885c74e892aebd10889e6157d21605286bf": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.25"},
	},
	"726f2c247b1042ce8cd6c5c0fa0ab589fcec407364320e8188a7fc8199e5202b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.5.12"},
	},
	"729d3fb6216f1912450b4b1e46768a7c5b0ab6210bb7f07670c83fc19c2e435d": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.9.15"},
	},
	"72bc7a932d8ff85dcba098860b8838324f9d4ab4c8be2eded52974ce40ef3db5": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.21"},
	},
	"740d7ac4fe13ea5e31237c8137d5402c776a8083962b02deb56466739c010a6a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.21"},
	},
	"74e40cf266397adebd19d155e15070152e5d68bb0bb358b210eec26372d38e9e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.30"},
	},
	"75d6c953b2ea95cbefb730bd59b290568f4f3327cea6a01256b39757a9ed0a24": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.17"},
	},
	"7638dd42963ae295425d7b61c6ba6892d29bbcaa228f4b293503c748ffd752f8": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.16"},
	},
	"766bd823640cc788902a1b0b2c4f475a78eae6143897a6bd456deaf0df9651d6": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.31"},
	},
	"77bf0d6522305b6f59d78b385dba789533c2b82ea3ce0cc831f3748c9e1e1899": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.5"},
	},
	"782af93181006dbde7122dd8de4ac714a62e53832393ee72cbe420c60fde550f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.4"},
	},
	"7a0eb08e48e7f1a8b43a626eeaf4cdd1a787765b78ba7448470991d7964d694f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.15"},
	},
	"7a122c81ae94c3f34a64c5a70a310d3270fbeb46824429f871cdb6c9998b861a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.5.7"},
	},
	"7b1e7ed3e2738315f854b7d911b7c1134164ea5e55d66f36fa60be234bdca9e3": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.2.6"},
	},
	"7ca669e4f053223112586b08645572f6824ac3bd438db313c1e46fb99d853f79": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.42"},
	},
	"7ca6fa81d95268c244a452facc767853af35af112a2de9cc9c5282592bb372b1": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.6.5"},
	},
	"7cc590aa28a6c3b1f02de525801fed67d5527037a8436146304e3a7c79d3d905": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.1"},
	},
	"7cd43b1bdeaf4a7343a058b16fd8195fc257f84a10f9cce2bd888a3e86929972": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.37"},
	},
	"7ced82d4a74f5c5b36767e0955e0d93e0f0972bc88f2bfe4d40c831a8806c29e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.0"},
	},
	"7d2a6c125b5ec8f37db93b3df811d8021aa06005801bf484e1d434bd983d83a6": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.0"},
	},
	"7d4a185ff25196cc79e7600190998ec2dc25c3a732f82cff10e7c8f16092ce05": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.29"},
	},
	"7d5c06ed703960b238050d87ce06a4bcac684af30293ba0a2656b673c5c84b25": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.19"},
	},
	"7df2253669010a441f9a5d454df2e57232574c86fb6e4cadbc58c587bbdf81b8": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.9.10"},
	},
	"7e3b86c3e3a9cd77902755ccc9d2252624b5d52edcedb80a7cfdbe7493eba758": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.63"},
	},
	"7e95d6693a7262337d4f3e691acf47979cd447fcdd557d85c61066fc0ef43d19": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.11"},
	},
	"7f7689e6d7a16179e3496aefa798793615fecfff346ebc2a2355ab0900a1b0e0": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.5.3"},
	},
	"7f8e878442e8958887ee9201c087167951249baa626fc2c329ece8ac639a768f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.3"},
	},
	"814a5a8ee3e9e501321515250492e20b2c8cb2ecd14280af039439e98c6b9cfe": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.24"},
	},
	"81813bf9fa70ccc28bb2745b474c139927b3fdec37ac9132a3cb6af38705a793": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.5.9"},
	},
	"81d4ab2b47ac53e5e69d6c09a0f1bbdba4cef2863d2418a6314d744bb1a654d6": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.23"},
	},
	"822b8e9315ec22a5dd0ed0b43ca0f15e93c7597a91b8ad764edd53941b0fc778": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.29"},
	},
	"82d779236a2e4f24ea279e2007cd888d625fe322155012038c06bb5877bf73ff": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.35"},
	},
	"82e4734b3bd81663ac93ab8c416dc91611133f5bb1bce052c0406e8c35c6c026": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.7.4"},
	},
	"83bf0629935b7ba1b53eb1eac50e3babb11b6bca57fc8ece320fb5cd21a66ae7": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.7.6"},
	},
	"83cef6faefee7353bdada8afae2222fb75aa342964e255df14e55fd812ee2ade": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.55"},
	},
	"843efb3d4d053204b1922bde8bc8d0290fa0270116eb708fa09baf5d05cacf99": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.5.10"},
	},
	"845349955994e0a8771f9a01a08c91862e155064248ec5aab8c12c94357bc203": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.7.4"},
	},
	"85106a1d11a7ce252aeb747bc3066edf0fe670b81c243b7d2c6724a1f14b96a1": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.10.0"},
	},
	"856f70e494d872e13fb0d49171f5ab3b007a4f59d802828403741eba4f1fb299": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.30"},
	},
	"85cae8ad2e6c265b60b88cf6d1187cf78c685852651171cee11285cbe788d0ea": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.31"},
	},
	"86894d3a9db498c2019b4f3ea7dae8728a305026e507eedc036637ac23523349": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.3"},
	},
	"8766ca8e769b28d2cb6ddaf9906506595537f0597b63bbe01948066965cde7a5": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.20"},
	},
	"8794c8b262c1b6156262632f386a83480a661ec08b40f9a0338049e31fcb2454": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.22"},
	},
	"87d6af8f335064b709024582cb751c351a0a7f1093d4e54481f900a61a4c14f5": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.26"},
	},
	"8986573cfd66d4255cc0fc39b29aace8b1375684a3ff1548dc9e8e381e93fa8e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.2.8"},
	},
	"8a3a66c5beb4e7f7bd8637aba10af113820e1750a6c47535481d2aaf9cacd6a3": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.9"},
	},
	"8bdf7fd57c37473a2254c2d7c01ab9d5b4f38f3bb467955d359fb2e54c38f2d7": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.21"},
	},
	"8c398f163dcc1c09cb2a06267e2f3d333276e308b99aac240e9d55c68287c29b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.11"},
	},
	"8ca992ea464de926b9ebfa82232ba59a4bd4df4afc21420ae5bc1fa84b47aa15": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.7.0"},
	},
	"8cd7ca25e0af7f2473312fd708e4c7e79266c4a4d6dcfd5c3b971e4f64662506": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.25"},
	},
	"8daf0690ce1eaae5abb3c0cfb57a5b448c92a170dd509e934c3b708eeebfce77": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.41"},
	},
	"8db47f50c2592c6fee9281c3d8e682278384a9207b4c7c2f70dbf613173e237c": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.20"},
	},
	"8f0450605d0fe501dfd62f917b9df8735d0bc902ed2356a4428ab3c1e01c4ed5": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.2"},
	},
	"8fab318eb26ce608f91011f2e7a09b1fcc4010ccb90570497cf19702ecb74eea": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.10"},
	},
	"8fc37c9c2f8f758b25a456f535f913b1a64dbc1ab6965bf90c0658b45f789e72": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.61"},
	},
	"90069c9b8b5679605784d86b4be648ce8f7f83a3463ee69b1ddffdf48cdbb298": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.1"},
	},
	"91819ad5ad648a2927c20009cee00d31c5d281258d78df65ddd830ddf604e0ec": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.6.4"},
	},
	"91d367ac7b1c45144cc1f6de7bcc5e96df437922f578cdc484bf24644a837015": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.4"},
	},
	"92fe882eb361789e6c530bcf1008ae7c2fc5651dee5fda62f9d4f186290c6add": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.21"},
	},
	"9312ffca6a1ca514b093f2b2c45582cce9de6ea18d36feb61fcd4f6370ffcf20": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.5.8"},
	},
	"932dd2b40fe26d3eef1947a357eecc8e755cd17fca1fd707cb5e882e66118488": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.11.0"},
	},
	"94c10ba8665537879830529885f50da7153a7d46109ee6e77515baaaa9746c7b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.3"},
	},
	"9618b7d9e3758e3643f328f5db76dddbc975907372038e10efba50900684163e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.35"},
	},
	"97237376350272865e08eedfbf3198e2ada749f723783ec39bb9899de482930f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.39"},
	},
	"9752b4ecf2998ef26db2fc1b055c085990d2dd5e91ff7d4b346000b18ff7783b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.4"},
	},
	"9776578a3021183b043188b02e24204965e19a9d75c02fd4da2eb44222b24649": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.32"},
	},
	"97ba8959c59c895b9993ac2a24e11f40ade7c4ffad33adbc31e5db59e1616c74": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.25"},
	},
	"97d06c1edcabd03178188388bdc1aedf693eb40f063a4a32c9586c0e5615c649": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.37"},
	},
	"98ffc6f4fd04f958ed0f5fba6185db6893a670a50908f15b10478ccd05cac196": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.7"},
	},
	"999e6ce423a7f8168fdfbe4e65916b32bff5c64e72ec47afd2a605b75f1e6f8d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.42"},
	},
	"9a37adc9706a60547d079799af88a9552f20b4ecbf399d1ec1a8ad2bfb7c7590": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.7"},
	},
	"9adc4f287e80d9f635c144f6abd6c2187f94742b03e1cc27b62aa1d119843835": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.31"},
	},
	"9b118a73452bfe822e07663d433a40fa44e4768703fdb9be2aa2294ff61aa553": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.2.10"},
	},
	"9b3ef598b5465eee921e108dca77c4a0b81e4fe28169c9ed40e37c57783150ad": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.6"},
	},
	"9b8b7f71a56e811f5cbc68dfddd391cec5cfbca5dc7694926224c2195a3ceb92": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.51"},
	},
	"9ba3d60ae2851e9672c99f012f6569c0f80c3187651f25954da18c8755792cba": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.33"},
	},
	"9bb0b1f384b0e7f0d86fb60be6fff32fe22f11c7d81f5f1c0ac01183abd28551": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.6.6"},
	},
	"9bfac6c8a5243ac55fbc1661b0bf699989eeab2e88b8300f3de256ba6746b0bf": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.15"},
	},
	"9c17f7d52eeea7b9b98d3397a05bd2544a99a43df7063b1ad33a4bc1cdfb9531": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.45"},
	},
	"9d01dd6603100a90f34ddb45c3d82364c93327ae89b655c0886777825c07408a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.34"},
	},
	"9ddc026590f43f584d5e072418d74169b87ff9d664cbb6d9d07bc41c84ceaf62": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.22"},
	},
	"9f811d940f696e281efc8304078b7e4828a2a5319808d116424011d8c6f6c0f4": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.36"},
	},
	"a01aeb26ac016b3b7e0b4337919a955df992b1dcf68929834b26f0d5de6efd32": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.19"},
	},
	"a02390c2d8dd383df82a7795bb7bbc40b5f62dda34726a2b80681f0a7818e25f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.28"},
	},
	"a0e398222e6ed7470b948ba826bf8eacf0c92828f90253ae37281d98ff460c6e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.2"},
	},
	"a2061e0fa2dfbb074e56a9dfada2d227ff405a3f80f8c84192a812d64534d549": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.16"},
	},
	"a2e9f173a63db6bedc2a626ab975856baada20a7906df38d2ff8fbdb7c71eac5": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.39"},
	},
	"a3670093265edb6c98bf18233b1771c7b345c4960d9e78d02f00953a465a8035": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.65"},
	},
	"a36d54aca40b41c144e7c72e79365d3f6d3374a0b38f1708fa521cf3f57e31f7": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.14"},
	},
	"a482f31dd72f4fa437838c486564adf831e7fff97e77a9f8df57cf0a1aba19ca": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.2"},
	},
	"a4cd6787d5efa8ade3c8189120643610f37e653c02f50c485a4039d3e0535695": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.23"},
	},
	"a685ea3ad626e5676787d61251633ce7ae860d7abebe90d26c39dbcdbd1bcb7f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.11"},
	},
	"a7172ebd897ec0bdd5896ef003956496e0b852fdde5d3e8ed44ec07394b8239d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.36"},
	},
	"a859c0d1c0ae79d0359d5e50100716b9e81112a752f0d9b9c28e1b1312ee0383": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.19"},
	},
	"a8aba898b18e9cbdacc28e1460948d4d7b2b09176c7c7d7cc33c62ab237b7b7e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.18"},
	},
	"a95f85f501499f93d5bd2eac1cfbf526d1fcd0f5b266dfb1c44e89604dc113b6": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.58"},
	},
	"aa4d38c51f50b5793a43083a7698161c402d678a00f91e5c5c8d4f190315156a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.18"},
	},
	"aa86127091855ec42181f5e0baa9501ae539ba31e0db7e4defda9d6f2e35bcab": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.7"},
	},
	"aac95bf8a33cc5e124661ae1ee55c2c1099b71f35240e27cf367cebd4e60da20": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.28"},
	},
	"ab436680162a7bb1a3340b41b96b667c52d2ad44b29ddf570ce3c102494cb383": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.22"},
	},
	"ab77934da39b689f5d4384a67691b99f12bd77c05e441a0c86b37c5b08ae851b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.11"},
	},
	"acd55c1c6a3412d92563d5900007b8e6d29e918abd1d4322b40c68cd2e5d94d0": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.43"},
	},
	"ad2bc0b4e758fb5be9dcba21f30c49a78833c2437b1c5f7fc01316f1565d3a4d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.32"},
	},
	"adc1efeabebbb73669ead16ba5e1a47a2d7092c43eb39586dd981054354ce00a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.26"},
	},
	"af94c47dd150063aaff2272623b0891d7229d1037c9db22cb9d3b36b61696fdb": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.3"},
	},
	"afe432b1d5ecbc9e428a5cd622239b228d72529c3ef8ca64a1c7783e8b30b81d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.20"},
	},
	"aff0e936fdf2350fc12907be91903d00ae41c60e7b790ab4c2b09a835e630319": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.33"},
	},
	"b05d18e10fde89ae767a34d3e71f0f97740f61fed6858897b38e63d181acca94": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.35"},
	},
	"b121ecb90adcb48d197c91630f0ab1dbf29b8dbb0c8fedcdb6671c9093e46ec2": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.0.8"},
	},
	"b1cf460a2baf2fbaffab860470be91ad47d51db221e995a1a6247ba02a8c8015": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.14"},
	},
	"b29eab61918f28211b024788704b2234b4ee9b29a12498437840c8732fcffe85": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.28"},
	},
	"b2ae6744ffb6d75b98294b8e9e3fcf08457d32fc02c1e378e59e4af0eab21977": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.13"},
	},
	"b33bf32f1f8f60e34be5dbe176ac77f8ac094d8d22dd9140e82aa643332c6a02": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.12"},
	},
	"b33e2f63f60cbb96223a806069a99413ade2e4fba98c06489cb00ec77667982d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.33"},
	},
	"b48947c676a53f168c17ec5d95f15149ada2a0a60fe745b1f53d1f5e3087d5a0": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.24"},
	},
	"b4c8a9038e05e76a24c5b1bf24f0031727d6418275d28dc1962bce2c69f28c34": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.71"},
	},
	"b54e3c1f66a38c1f80dc07bcfd1273f2e71743749c8aa47e923f590869bd0c52": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.10.4"},
	},
	"b605031e461eec4f526fc7ae3d2eac5f63b2375b37810ae0a6b5312d9feb8b85": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.18"},
	},
	"b820072df7baefaa9e3afd0a6234ec981372b4ef1bace1d5f40852e47dcb0fea": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.12"},
	},
	"b836f08db6c6b390372261d812d37f544d2749942e5683d7e6a597e1866fdacb": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.7.2"},
	},
	"b8a5da148a172d9124eef42891c124e740bc1bd96370c62d00f3ed8d1759956d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.2.1"},
	},
	"ba0dc01ea6aed7ee65289f25dfdf5b18b573b2bb6b34f107963cd35ba4a2e857": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.9.17"},
	},
	"ba2414067ed1a0b6121d2eadd437a69dc48bc18aebd60c445c6f292022147772": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.10.2"},
	},
	"ba2c3bfa64e78026c49cd2e1a12c14176eed963b18e69612201529c2ca1792d7": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.26"},
	},
	"ba82ba72a0ed408e811787ffc63e1c77577271534138ced2b717c18cfae6616f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.7"},
	},
	"bae9a07e4e3b32655b4ce2557cb921bd95ad099981dd73c9c399c55862a8a885": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.5.4"},
	},
	"bb685200411ab4a7e3790f9626ede3cb512ceec6d1fcfe0f90e3d7a8de0b9e4e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.5"},
	},
	"bb95cd16d76ea8b84020a1d34da0507128820b3232f3575bee9f74a77b3c8c5d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.16"},
	},
	"bc2dd541f4f6211fb175e61b837fe3851568ba1bfab228a49a958a0e8ad8288a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.8"},
	},
	"bdcd93b6a56cb785d5171daa6fe2b1716d9f76db446ee9c666ef78229fabc497": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.3"},
	},
	"bdd5f0e83be169ffce9a32c9eb5290ebd0f1c08f32e66433eb3d2cd1df27e2b9": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.8"},
	},
	"bed084ee7e01ef4ded069eef627b9d74a2d67ab247fc21a907ce50dca363570e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.74"},
	},
	"bf468a9b3474abf00d06031d7f14aa226d8fd35c93b45fc88b6ac67821b93ed3": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.10"},
	},
	"bfba1cf8750b753ff5dcfc4531de324a8c3f06c4ec659c8f51457fb96c14c33e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.2"},
	},
	"c0f39eb2967f8cea15b87fd3472e26ec778720664fde12a54bd4ad12c125d0bd": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.3"},
	},
	"c13146db8e9a8badb0228e2542c01c49e31921994da294b7f96b8381d104ec9d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.47"},
	},
	"c404b7f94a47e7bc81885edf845d87e133002c9824b44b6eaa3399ce1b07f13f": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.7.3"},
	},
	"c472b2d2affd375ba2192f78556efe23f00bdcbcb46f698517eebdedf11ac7c1": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.2.7"},
	},
	"c56ec9ab483c28135ff229664123dfb5442fff2c35e12cb49f5dcfe8d40b4025": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.58"},
	},
	"c5e4f7e2a0fce6ed8532d2dbde97f3803a76f922e8d666278555269721e81807": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.62"},
	},
	"c5efee2617f4a0ddaa40babaf92b2a31b7e302e3cb025aa71cc2d7b170f39d3d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.27"},
	},
	"c61d7101ee2a8ec78dfa9dbeb16494eb31c8ec0f209a3d584bbeb89baceb94bc": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.17"},
	},
	"c6bce80931304e169b61588cf2f7940a324325f1b4e5fece77e4158d996bffd5": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.40"},
	},
	"c8d836190dc536f312f5037aa77b47c7bbdfaf93a7fd521002f9d44b8f2db37e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.7.9"},
	},
	"c9217cf12f626162d9c5a3be4308d1d86bc88998cc86531469a60f6138ac0fdb": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.15"},
	},
	"c9422700d5aa75f886cfcea44233388601c1e8759365bd64d755aedbcdd2f6bf": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.32"},
	},
	"c94ae255ce909dee1db9eaa3d7cc64557ad9299a469a96026e556d81f3f21f6b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.7"},
	},
	"ca17793b617e2860110c2d87ec28661c96b85d04b1a2d5e861b31964c3f1e9f3": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.34"},
	},
	"ca574c4591982f836bd397389a94e77ffa5d5e44edbe226303d86550d5fc915d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.9.0"}, {"github.com/aws/aws-sdk-go", "v1.9.44"},
	},
	"ca8e018c638e0e85abce5563d75b92910f88c662c5dac469650c103bc6e340b1": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.49"},
	},
	"cb010e8f46f6ab7b800387d0d5f3443bdb526fa9186ae813af37aef95e44bacb": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.59"},
	},
	"cb1c4085a562ddf49db0cd25c2cb3080c10d1875315215fa59298b17aa1eb33e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.66"},
	},
	"cb1cad870c2552672c9012abb89de0ae518f30be4a932e5139d8e726eb74a15f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.20"},
	},
	"cb2a904974fbf01db3692e7945a88a3b176a892793f8c66ffa7a5c9a3e2c97ad": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.12"},
	},
	"cbb2943e5502cdd151eee1d6643f407af8113b3637c45919e98340a5feb31a63": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.39"},
	},
	"cd1f3cbd5a155628ac3c3644b368bcde18f59d6a85ebb13a8edf9c1d1578e680": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.38"},
	},
	"cd68b3e4ec5d3fca144be7c3539e4bf9c6053bfe6f2e2396a888db248e3cbd3d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.7"},
	},
	"cd732ddad3a59e486f2b19f88d2be2ce1eb75ec112323959d3ea0f8fd1130875": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.26"},
	},
	"ce30bddfdb91f805313a0e2667bf1a3c1da669d8ad67b1e9a30f901046894c51": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.13"},
	},
	"ce4c670eed03ad91f82e813208d69a94f1353d4002c00d35949f9223783c2123": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.52"},
	},
	"ce5c8dd103671fb3e122d80c5bd52a0f448ddd9c6939530032524138b3ca3ee8": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.53"},
	},
	"ce6c3731b313f7efd558297b97a37e6335fca86d78cb72769d00ca5f3e0b2c09": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.27"},
	},
	"ce711d06869e6292401f47a072a4542e9820fe808aac234a82b830b3c1881483": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.30"},
	},
	"ced8d770cc0cdb0e4fbb2781ef521dd065ab1d30272b23deac54f3aeaec59019": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.16"},
	},
	"cf828b5564ae3f2ee6b1bbb3adc1bab0012c7a6df12aae29ad513718b70696f8": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.0"},
	},
	"d07999a8116a78797cd51dd20e43eb03f286d6e06e2ecbb2431293552085dbea": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.10"},
	},
	"d0f74a3a6da991ea1b105fa8779d8e4c51a114bad24e4372161eb5820a637b47": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.16"},
	},
	"d182011c210e5bb52d218631880ab660db7470b386470c482ba32b58f76efd97": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.69"},
	},
	"d21fac302382ef6b3eba71fe4c7fba8ce43d372488eecb15dec7f039c0a4f8e2": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.21"},
	},
	"d2c0f9ce7cedfc80aafd7b4c2ecd84b80a56d422acacbcd86bd63c489488f33a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.11"},
	},
	"d34db4acb9fb08d862e8dcc1f6de37fdf565240b2236c0f1cb824e76ce2ec9be": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.44"},
	},
	"d362a7923097bea49e236f33ffb0ec96a2d63daab19ef8804174ef73b9a15182": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.14"},
	},
	"d3d5d3510f57ac2eeb742096faafc004d0853d4e2fed1900a828df80733e7aeb": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.30"},
	},
	"d53259b1aab5464fc6ded0d8f6b60a2249c96a2d6f3b5e8bfb854d70f3317be1": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.73"},
	},
	"d55f1e5b5738e08bab3bba904dc085b1cc40a66c13524fafa154206f96bbff1d": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.9"},
	},
	"d61bac5bfbdee5372f07be040119096b0dae533b5b940a7a2eb539e48df944e5": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.6.8"},
	},
	"d6463a302a09eb3e44ef93c6b87ef2b2d90a0b8a514b5d8655718c5fa8bf4d12": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.50"},
	},
	"d65e4d5afb087b25889fa876a10551f84dac2f8998506d221efd6494206d8c33": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.64"},
	},
	"d66262052a1d8d9e3e81d0c2b6d8cb0bfbb749af2d7b3161a432aadb8bc767a1": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.27"},
	},
	"d7a3261843094f838a51ff6eacea3f1e4a7b81649a6969e7fd5a175c85a504fd": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.18"},
	},
	"d7f1bab2eff9d993284f2c8fbd778a4377176ce6827f2bdc98e6786cc38b878a": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.9.12"},
	},
	"d858942c5796c5ee69278b59f60bb7185d3c08e39dcb5e84c96e84fd1aac35bc": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.9.8"},
	},
	"d87b79ab98cf01d0628c4d96277718c27b64223ffeb8334c315cd8b609c5264c": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.2"},
	},
	"d907f146c13eff309c1d1ee8468ff2821e93105734353d016044c1570335b724": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.48"},
	},
	"d9d826fa574ba6ba8cdd19b0caf9e752601c8d1324f7e6f895570d6ccb8e11ce": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.2"},
	},
	"da39e3800531c2ffc16792cd1d99b28ec5573701e977cfaa4fd3192e09e67969": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.13"},
	},
	"db4dcebc35e050bdf86117a6ea9ec662f1f9f90b7506b8e2e39c53094b8cb70f": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.70"},
	},
	"db7832bf78760429656f71cb0351a5f4f1f935a9f997163a4ce2cdf189fb771e": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.9.9"},
	},
	"dbf7d495fed7b8e912352d4731fc48ea5fc76efb5f3680c7b560e752bd532f86": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.24"},
	},
	"dd688d526fe1acb41417e3cabb54ef9fcbe72508705478569d7a62f255adfeda": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.38"},
	},
	"dd946f6a7c3f719f71c57835b624a90936e485b7cd37f596408dc33c9eb58cac": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.29"},
	},
	"df65b10f538ab7aff99c7e3f83cfe34b89eb003eddec3c140dac7750d3d73fba": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.9"},
	},
	"df90a88e0c32d5f01e95a91ca4236a3e03a4d32801143415bc1a644aed210b80": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.41"},
	},
	"dfcef1682cd0caa089c89d9894351f9a796fa977c95fe3bf298437ed9f1b5b52": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.9.7"},
	},
	"e01a71d3de71146dcd91ccd0b849b487c222e0619c2c42e240c06f442dc7c751": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.19"},
	},
	"e0931892923fa013a833b081990884239062691eeaa07b8dde0c3a96816ffb91": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.0.5"},
	},
	"e0bc39c5d159021770ec13ee4893f5e8ed3305f1e645eded670d4bcf3c5641a8": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.0"},
	},
	"e119d051768d87de66ff4e2727232f7de44c4162aeea9afd94c3b36711241ca5": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.11"},
	},
	"e1b41a770414ed40e9bf119f418a780fc735cdbbcf42a474fc35feccaf00da82": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.15"},
	},
	"e1d08b2bf8b1887233f4e89d9df269db5ddacb6ceee5c01481b49947f1bf5cb5": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.36"},
	},
	"e2062fab0e53fa5c702b4c942a4a25b83f9bebce5fb3448e91b299dbbbc3424b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.29"},
	},
	"e2164a8f836294fb68e2f01b198fec3adf636e1a387e9d5922bdac89bd03f8cd": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.8"},
	},
	"e2332bf793196d7b05747214fcedd474503df96701e4005156c30eef05f1a2a6": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.15"},
	},
	"e332eb75ecea0041794df292a08eeabb8f6c596039dd0e796a5021cf56457731": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.20"},
	},
	"e3a49e7a64d75128384161cbbd65c2a97b5188ca3791c9bd4c935aacdd237855": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.50"},
	},
	"e5124f094a85897a0cd0fcced4e163a4b9b40f6d818b4ee487a8592841a301d0": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.9.5"},
	},
	"e6259b965f3109ebb10db93218941dd54bde526943e99d94eb095ed0cac2b0e7": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.22"},
	},
	"e690b0559769f476dcf9229fbc8292b1cfd24138abb8091e61856a26de9999a4": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.18"},
	},
	"e696958a4263caf2b3f15d19450e66c6d7ecbee7849dcdf8c8b82c45273ae0a9": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.29"},
	},
	"e732ef222a8b2a0ffe8067ea651bd4d5306d0f227c34ceba1cc5db570e1afb07": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.56"},
	},
	"e7ce23fb7fbea352f56ceda1f3d2aed209481e69629d72a7f702882e50e9bb5e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.9"},
	},
	"e8b855a2c94dbf3dd30e9a23bb5df5b38bfd6315cc3d03e2844a3092829cebe2": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.75"},
	},
	"eae8ee1888d4d8681f131424e2c9b6923dcc9a12b77b8d99f3bdde3ab590b599": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.4"},
	},
	"eb1c93b7aafb5767201e0d8f933cf9cae0f93e18afcd8b9280d1486228c7cc32": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.6"},
	},
	"eb2980a66df4153cf037d1f9fb8c79db9cdbd58a913ea2294b679f6241aa4da0": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.33"},
	},
	"eb33e9f10145c827dc58198658dd78edb50568108186d6b1659dcf05371f10f9": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.40"},
	},
	"ed4309d0d51b01b596de6ebc4f6275e47d24e6fbd3b19969eae59f7bb492f29c": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.23"},
	},
	"eddb064e987b8a441e2f0ab8b635d331fbbfa21342ec7c6975852a1749ea9011": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.5.11"},
	},
	"edea33bc34a244dc8e73f82272955be20e017b13316f4657b612c5dca2307bd8": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.3.0"},
	},
	"eed74a5552785f1f8c14541ab48ed0cd166e18f4a361f5ad1d35b39e00a61e4e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.5"},
	},
	"f0afa0f13fd8f3ed26c91b4994c9737b3463dc9e5f28c961ebd8415b9bbeb849": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.17"},
	},
	"f1660a7f7e849eeec41a83527c02593705c82a6b9f546727050a27815a88ce59": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.47"},
	},
	"f1815af9489d5254297b9671fcd7c8cf087083821268178e62fee7959fd7604c": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.31"},
	},
	"f2d55933bb62973a5659b8ce51469edc130127460889ccf26d9373ddcfb80746": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.18"},
	},
	"f3fe19b65dab0d023751fa1cb4e4951907bfacf948527577f6c19bbfea505870": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.12"},
	},
	"f4046f620abc58e5f69fbaf1fd302cece178a9f2241cd099756fa213cd45453e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.42"},
	},
	"f4319bfc9a8cc81cae83a435a44322db78ec9605c4589006ce50dde99c1c6329": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.28"},
	},
	"f46fd31e74c98730b2f6d9e5bd01cab2e6365dc1bd38edadcbc5d0713a9dfc56": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.0.4"},
	},
	"f4f5fcb0cd567068065a61bc6a055521acbd3ddb32dc7a20fb966c838101d976": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.6.2"},
	},
	"f53d56e7aab4c0acf97ea01925f56174bcc66b435bc01ee54313562cf05d0975": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.6.0"},
	},
	"f5e5e9c9882c365c076b2dbf342b750505a98902a4c1b7070567ecde83ffeceb": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.4.21"},
	},
	"f68f0f7f0a7c758709daa4ab286696e2ddc5ec5281c7258abf369e12138905d2": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.26"},
	},
	"f7370500e2e3f7ba04b89789996d153efa9888f0f5c9aebdaf5a5dd46ff10361": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.13.6"},
	},
	"f83760c92c83ca1c4b8a658e10a208bbd74f98596425ee7e8c5716b9b7b87217": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.48"},
	},
	"f86211b26e0d08dcc478325ed6366c65ba06e2467d482e5233376bcd1b5a0d07": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.14"},
	},
	"f8b886081d445af9e9b8a28fa38b0d5c4ff9bc792b069d960df1a6984a305869": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.14.7"},
	},
	"f920225c4455dd6c6e003455a0a13c5209f124fa25006d0b5689a2e17395cc8b": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.54"},
	},
	"f9b57c361528b04f82c74f474708cb9f0bd066d063644c1ae5fccae107a16870": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.15"},
	},
	"fa778c167772a3ef8d409e8039d73cc2f07bb8d040ade4f8b1c72ce0b317664e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.8.25"},
	},
	"facf252e38bac6853a098dee7fccd6424627451dcaec36d8d6dfcbbe5c68c39a": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.13"},
	},
	"fb7e4ba88db2f40423ac9a8a64ae1c0bed170999112109bab0e81be1cf70b9d7": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.5.5"},
	},
	"fb8476c9ec1acea3cd9cbf3cc12279144921f64447e1f06bf55b8ec61be6f7d4": []Modver{
		{"github.com/aws/aws-sdk-go", "v0.7.2"},
	},
	"fbef79a719172c6fca21d448e9d9f8e18c2ccbd15780c0b5f94f6f813f060041": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.10.24"},
	},
	"fc48b8a388e1f0dc9deda9bae8215211fff0e06fc7b1c610a529e01759680cc2": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.1.19"},
	},
	"fca386056bdc08769b70d8bd8d706138238c1c36328bf24596c42b864c02a89e": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.3.1"},
	},
	"fcb9d2ebdb73d1797db76332b0c35f2f65aaebc8f0ae55869b139a07f82316f4": []Modver{
		{"github.com/aws/aws-sdk-go", "v1.12.34"},
	},
}
