# Copyright 2020 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

FROM node:14.15.1

WORKDIR /pkgsite

ENTRYPOINT [ "npm" ]
