// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package client

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"sort"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "update generated files")

// TestTypesUpToDate verifies that types_gen.go is up to date with
// ../../../../internal/api/types.go.
// If run with the -update flag, it updates types_gen.go.
//
// This test effectively acts as a generator to copy API types from the
// internal/api package to avoid exposing internal packages or creating
// circular dependencies, while keeping them in sync.
func TestTypesUpToDate(t *testing.T) {
	srcPath := "../../../../internal/api/types.go"
	genPath := "types_gen.go"

	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, srcPath, nil, parser.ParseComments)
	if err != nil {
		t.Fatalf("Failed to parse %s: %v", srcPath, err)
	}

	// First pass: find imports
	imports := make(map[string]string) // local name -> path
	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.IMPORT {
			continue
		}
		for _, spec := range genDecl.Specs {
			impSpec := spec.(*ast.ImportSpec)
			path := strings.Trim(impSpec.Path.Value, `"`)
			localName := ""
			if impSpec.Name != nil {
				localName = impSpec.Name.Name
			} else {
				parts := strings.Split(path, "/")
				localName = parts[len(parts)-1]
			}
			imports[localName] = path
		}
	}

	neededImports := make(map[string]string)
	var typesToCopy []*ast.GenDecl

	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		if len(genDecl.Specs) != 1 {
			continue
		}
		spec := genDecl.Specs[0]
		typeSpec, ok := spec.(*ast.TypeSpec)
		if !ok {
			continue
		}
		if _, ok := typeSpec.Type.(*ast.StructType); !ok {
			continue
		}

		typesToCopy = append(typesToCopy, genDecl)

		ast.Inspect(genDecl, func(n ast.Node) bool {
			sel, ok := n.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			ident, ok := sel.X.(*ast.Ident)
			if !ok {
				return true
			}
			if path, ok := imports[ident.Name]; ok {
				neededImports[path] = ident.Name
			}
			return true
		})
	}

	srcBytes, err := os.ReadFile(srcPath)
	if err != nil {
		t.Fatalf("Failed to read %s: %v", srcPath, err)
	}
	before, _, ok := bytes.Cut(srcBytes, []byte("package "))
	if !ok {
		t.Fatalf("Failed to find package declaration in %s", srcPath)
	}
	header := before

	var buf bytes.Buffer
	buf.Write(header)
	buf.WriteString("// Code generated by types_test.go. DO NOT EDIT.\n\n\n")
	buf.WriteString("package client\n\n")

	if len(neededImports) > 0 {
		buf.WriteString("import (\n")
		var paths []string
		for path := range neededImports {
			paths = append(paths, path)
		}
		sort.Strings(paths)
		for _, path := range paths {
			buf.WriteString(fmt.Sprintf("\t%q\n", path))
		}
		buf.WriteString(")\n\n")
	}

	for _, decl := range typesToCopy {
		var specBuf bytes.Buffer
		if err := printer.Fprint(&specBuf, fset, decl); err != nil {
			t.Fatalf("Failed to print decl: %v", err)
		}
		buf.WriteString(specBuf.String())
		buf.WriteString("\n\n")
	}

	expected, err := format.Source(buf.Bytes())
	if err != nil {
		t.Fatalf("Failed to format generated source: %v", err)
	}

	if *update {
		if err := os.WriteFile(genPath, expected, 0644); err != nil {
			t.Fatalf("Failed to write %s: %v", genPath, err)
		}
		return
	}

	actual, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("Failed to read %s: %v", genPath, err)
	}

	if !bytes.Equal(expected, actual) {
		t.Errorf("%s is out of date. Run `go generate` in this directory to update it.", genPath)
	}
}
